using USAMKO.Core.Constants;

namespace USAMKO.Core.Domain;

/// <summary>
/// Represents a content item in the library
/// </summary>
public class ContentItem : AuditableEntity
{
    /// <summary>
    /// User who owns this content
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Navigation property to user
    /// </summary>
    public virtual User User { get; set; } = null!;

    /// <summary>
    /// Content title
    /// </summary>
    public string? Title { get; set; }

    /// <summary>
    /// Content body/text
    /// </summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Content type
    /// </summary>
    public ContentType ContentType { get; set; } = ContentType.Text;

    /// <summary>
    /// Media file URL if applicable
    /// </summary>
    public string? MediaUrl { get; set; }

    /// <summary>
    /// Thumbnail URL
    /// </summary>
    public string? ThumbnailUrl { get; set; }

    /// <summary>
    /// Media file size in bytes
    /// </summary>
    public long? MediaSizeBytes { get; set; }

    /// <summary>
    /// Media MIME type
    /// </summary>
    public string? MediaMimeType { get; set; }

    /// <summary>
    /// Media dimensions (width x height)
    /// </summary>
    public string? MediaDimensions { get; set; }

    /// <summary>
    /// Tags for organization (JSON array)
    /// </summary>
    public string? Tags { get; set; }

    /// <summary>
    /// Whether this content was generated by AI
    /// </summary>
    public bool GeneratedByAI { get; set; } = false;

    /// <summary>
    /// AI model used for generation
    /// </summary>
    public string? AIModel { get; set; }

    /// <summary>
    /// AI generation prompt
    /// </summary>
    public string? AIPrompt { get; set; }

    /// <summary>
    /// Content category
    /// </summary>
    public string? Category { get; set; }

    /// <summary>
    /// Content language code (ISO 639-1)
    /// </summary>
    public string Language { get; set; } = "en";

    /// <summary>
    /// Sentiment score (-1 to 1)
    /// </summary>
    public double? SentimentScore { get; set; }

    /// <summary>
    /// Content status
    /// </summary>
    public ContentStatus Status { get; set; } = ContentStatus.Draft;

    /// <summary>
    /// Number of times this content has been used
    /// </summary>
    public int UsageCount { get; set; } = 0;

    /// <summary>
    /// Last time this content was used
    /// </summary>
    public DateTime? LastUsedAt { get; set; }

    /// <summary>
    /// Additional metadata (JSON)
    /// </summary>
    public string? Metadata { get; set; }
}
